nelmio_api_doc:
  documentation:
    info:
      title: Publisher API
      description: API for working json document
      version: 1.0.1
    components:
      securitySchemes:
        Bearer:
          type: http
          scheme: bearer
      security:
        - Bearer: []
  areas: # to filter documented areas
    path_patterns:
      - ^/api/v1
