controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_login_check:
    path: /api/v1/auth

nelmio_api_doc:
    resource: '@NelmioApiDocBundle/config/routing/swaggerui.xml'
    prefix: /api/doc
